### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by ishani-rgb** [YuriSizuku/OnscripterYuri#2]
Firstly congratulations! This is the most complete onscripter port anyone has seen in years. I have a single question though?
Can you add support for wordwrapping?
It will be a huge help to translate Vns to english.

**Comment by ishani-rgb** [comment]
https://kaisernet.org/onscripter/bounty.htm

**Comment by YuriSizuku** [comment]
As the ONS engine is designed to use half-width charactor as command. It might be hard to use English word directly. Could you please show me some of the English game or demo ?

**Comment by lochana-Dineko** [comment]
https://www.mediafire.com/file/gxdyy95irfs6hyq/Tsukihime.zip/file

Tsukihime is one of the most well known ones. I don't really know if it's possible practically.
Normally Onscripter-en uses " ` " as the character that signifies the beginning of text

Example :
`Hello this a test text written to show wordwrapping`@

Onscripter already has a mode that supports this with the "English" Command in the define section, but it doesn't show spaces and is incomplete.

**Comment by lochana-Dineko** [comment]
Here is a link to the source code of ONs-en https://kaisernet.org/onscripter/releases/onscripter-en-20110628-fullsrc.tar.bz2

and the script used in the English version of Tsukihime.
[result.txt](https://github.com/YuriSizuku/OnscripterYuri/files/11007547/result.txt)

**Comment by YuriSizuku** [comment]
Thank you for providing the material.  I understand the English format now. 
Next version might be avilable for English text. I need to do some test on it.

**Comment by lochana-Dineko** [comment]
Wow. I'm speechless. Thanks! Happy that we have a good version of Onscripter at last!

**Comment by gitnerd1hez** [comment]
my unformatted no regret inducing reaction
Hello
- I'd just like to interject for a moment. What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. As per https://www.gnu.org/gnu/incorrect-quotation.en.html
- Github moment
- vscode android studio, and docker
- it is illegal to tweak a playstation vita
- Why the fuck is the project using cmake and python - even if it is to build a web site
- at least there's 32 bits executables
- 'apt-get' are we in the 2010s rn
- Jap *nvm chink* taking chinkware as a base? are we in an alternate reality right now?
- at least it's sdl2, no more library problem I guess
- Chink icon, bland and copyright violation if you will
- Web implementation, seriously?
- unknown games as web demo and possible copyright violation unlike for example the kirikiri-sdl2 demo
- Android application on the google play store but no apk or f-droid publication, is this chink retarded
- Where are the extra features brought by ONScripter-EN?
- Blank compatibility list
- Nobody needs lua script and animation, really
- There's no command to change the font in-game
- Probably still doesn't allow extra modified letters with diacritics, take it as a pro or a con, as you wish

https://redirect.invidious.io/watch?v=tAb7OID5lt8

**Comment by gitnerd1hez** [comment]
btw ew fuck yuri

**Comment by YuriSizuku** [comment]
> my unformatted no regret inducing reaction Hello
> 
> * I'd just like to interject for a moment. What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. As per https://www.gnu.org/gnu/incorrect-quotation.en.html
> * Github moment
> * vscode android studio, and docker
> * it is illegal to tweak a playstation vita
> * Why the fuck is the project using cmake and python - even if it is to build a web site
> * at least there's 32 bits executables
> * 'apt-get' are we in the 2010s rn
> * Jap _nvm chink_ taking chinkware as a base? are we in an alternate reality right now?
> * at least it's sdl2, no more library problem I guess
> * Chink icon, bland and copyright violation if you will
> * Web implementation, seriously?
> * unknown games as web demo and possible copyright violation unlike for example the kirikiri-sdl2 demo
> * Android application on the google play store but no apk or f-droid publication, is this chink retarded
> * Where are the extra features brought by ONScripter-EN?
> * Blank compatibility list
> * Nobody needs lua script and animation, really
> * There's no command to change the font in-game
> * Probably still doesn't allow extra modified letters with diacritics, take it as a pro or a con, as you wish
> 
> https://redirect.invidious.io/watch?v=tAb7OID5lt8

Are you seriously ?  Pelease read the readme file carefully.  
I must emphasize something  here.  This project is based on onscripter-jh, not the en version.   

- We often called GNU/Linux as Linux.  

- What do the Github moment ? 

- Vscode, android studio is for development. Docker is an alternative for build. 

- Why is illegal for playstation vita ? We use the un official vita sdk.  This is maintained by community. 

- Cmake is very convinent for the C project. And python is just a tool to make index for website. 

-  As for the 32bits, I like it to run on the old platform. 

- I just like `apt-get`. If you like `apt` you can replace it. 

-  Although this is an SDL2 application, it still have many problems to deal with to port to other platforms. As for the web, you need to consider about the async and loading problem.  And also there are somethings to consider in detail. Please checket the commit history.  

- This web demo is just a simple demo. And it has no copyright problem. 

-  We have provide the apk in the release page. 

-  This is not aimed for English verison.  The implementation is mostly based on gbk version. 

- This is beacuse nobody report the problem. I have no time to time. So that I leave the compatibility list blank. 

-  You can change the `default.ttf` before loading the game.  I don't think chnaging font command is necessory. 

- You don't need the lua script and animation. This doesn't means others don't . If you don't like it,  it won't bother you if you don't use. 

- Finaly, this is  not aimed as En verison. So I didn't consider `modified letters with diacritics`

**Comment by YuriSizuku** [comment]
> btw ew fuck yuri

> btw ew fuck yuri

Just for clarification here, I am not obligated to do anything for you or for anyone. If you have suggestion and complain, then it’s up to me to listen to it or not. Next time before you speak I hope you may consider your word more thoughtfully as a responsible adult.

**Comment by UjuiUjuMandan** [comment]
Those comments are basically spam. @gitnerd1hez you should be blocked from the repository for your language.

I feel regrettabe for seeing this psycho when looking up if an F-Droid task exists.
